### ISSUE TITLE
Updates seem to have broken something

### ISSUE THREAD

**Issue by tcholston** [UbhiTS/ad-alexatalkingclock#10]
Since the updates it seems that I am not able to get Alexa Talking Clock not working. The kids with the CornaVirus were really finding this handy. 

This is what I am getting in appdaemon.

2020-04-25 21:58:58.182743 WARNING alexa_talking_clock: ------------------------------------------------------------
2020-04-25 21:58:58.183577 WARNING alexa_talking_clock: Unexpected error running initialize() for alexa_talking_clock
2020-04-25 21:58:58.184296 WARNING alexa_talking_clock: ------------------------------------------------------------
2020-04-25 21:58:58.187903 WARNING alexa_talking_clock: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 145, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 276, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/appdaemon/apps/ad-alexatalkingclock/apps/alexa_talking_clock/alexa_talking_clock.py", line 31, in initialize
    self.alexas = self.args["alexas"]
KeyError: 'alexas'

2020-04-25 21:58:58.188315 WARNING alexa_talking_clock: ------------------------------------------------------------

I have reinstalled both appdaemon, alexa talking clock, and alexa media player. Everything works except the talking clock. 

Hoping this is just me and not breaking for everybody.

**Comment by UbhiTS** [comment]
the apps.yaml config structure has change from v1. to v2 ... please see the below link

https://github.com/UbhiTS/ad-alexatalkingclock

The new config section is given there. Now the app supports multiple alexas. so instead of giving the alexa as 
alexa: myalexa

you need to give as 
alexas:
  - myalexa

https://github.com/UbhiTS/ad-alexatalkingclock

you can have a look the the above link
