### ISSUE TITLE
Unexpected error running initialize() for alexa_talking_clock

### ISSUE THREAD

**Issue by markbooth73** [UbhiTS/ad-alexatalkingclock#5]
Installed app from HACS and running HA 0.108.1, AppDaemon 4 

Version 4.0.3

APS.YAML
```
alexa_talking_clock:
  module: alexa_talking_clock
  class: AlexaTalkingClock
  alexa: media_player.mark_s_echo_dot
  start_hour: 9
  start_minute: 0
  end_hour: 18
  end_minute: 0
  announce_hour: true
  announce_half_hour: true
  announce_quarter_hour: true
```

LOG
2020-04-09 15:04:11.732667 INFO HASS: Connected to Home Assistant 0.108.1
2020-04-09 15:04:12.956509 INFO HASS: Evaluating startup conditions
2020-04-09 15:04:13.028843 INFO AppDaemon: Processing restart for HASS
2020-04-09 15:04:13.030227 INFO AppDaemon: Terminating alexa_talking_clock
2020-04-09 15:04:13.036417 INFO AppDaemon: Initializing app alexa_talking_clock using class AlexaTalkingClock from module alexa_talking_clock
2020-04-09 15:04:13.048411 INFO alexa_talking_clock: INITIALIZE start:2020-04-09 14:45:00.045255, frequency:15, times:[0, 15, 30, 45]
2020-04-09 15:04:13.052637 WARNING alexa_talking_clock: ------------------------------------------------------------
2020-04-09 15:04:13.053344 WARNING alexa_talking_clock: Unexpected error running initialize() for alexa_talking_clock
2020-04-09 15:04:13.054017 WARNING alexa_talking_clock: ------------------------------------------------------------
2020-04-09 15:04:13.055367 WARNING alexa_talking_clock: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 145, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 276, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/appdaemon/apps/ad-alexatalkingclock/apps/alexa_talking_clock/alexa_talking_clock.py", line 30, in initialize
    self.run_every(self.time_announce, self.next_start, (60 * self.frequency.interval))
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 191, in inner_sync_wrapper
    f = run_coroutine_threadsafe(self, coro(self, *args, **kwargs))
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 285, in run_coroutine_threadsafe
    result = future.result(self.AD.internal_function_timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/site-packages/appdaemon/adapi.py", line 2476, in run_every
    raise ValueError("start cannot be in the past")
ValueError: start cannot be in the past
2020-04-09 15:04:13.056037 WARNING alexa_talking_clock: ------------------------------------------------------------

**Comment by UbhiTS** [comment]
Everything looks good to me, maybe you have an appdaemon 4 configuration issue. Can we do a live session over teamviewer or chrome remote desktop ?

**Comment by markbooth73** [comment]
Hi, is teamviewer on github?

Sent from Yahoo Mail on Android 
 
  On Sat, 11 Apr 2020 at 21:44, Tarunpreet Ubhi<notifications@github.com> wrote:   


Everything looks good to me, maybe you have an appdaemon 4 configuration issue. Can we do a live session over teamviewer or chrome remote desktop ?

**Comment by markbooth73** [comment]
Hi again, okay, I have chrome remote desktop installed and can send you an access code when your available?

**Comment by UbhiTS** [comment]
sure, i'm ready

**Comment by UbhiTS** [comment]
you can please call me @ +1 408 409 5540

**Comment by markbooth73** [comment]
I am in the UK at it looks as there is an 8hr time difference, are you on WhatsApp or Skype, Zoom?

**Comment by UbhiTS** [comment]
whats your skype id ?

**Comment by markbooth73** [comment]
mark.booth@yahoo.co.uk <mailto:mark.booth@yahoo.co.uk>

**Comment by UbhiTS** [comment]
issue fixed
