### ISSUE TITLE
TimeoutError

### ISSUE THREAD

**Issue by stefagi** [UbhiTS/ad-alexatalkingclock#6]
Hi,
your system works for me, speaks correctly, but in the error log I always find this message:

`2020-04-12 21:00:10.065653 WARNING alexa_talking_clock: ------------------------------------------------------------

concurrent.futures._base.TimeoutError
    raise TimeoutError()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 441, in result
    result = future.result(self.AD.internal_function_timeout)
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 285, in run_coroutine_threadsafe
    f = run_coroutine_threadsafe(self, coro(self, *args, **kwargs))
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 191, in inner_sync_wrapper
    self.call_service("notify/alexa_media", data = {"type":"announce", "method":"all"}, target = self.alexa, message = msg)
  File "/config/appdaemon/apps/ad-alexatalkingclock/apps/alexa_talking_clock/alexa_talking_clock.py", line 95, in time_announce
    funcref(self.AD.sched.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 766, in worker
2020-04-12 21:00:10.063241 WARNING alexa_talking_clock: Traceback (most recent call last):
2020-04-12 21:00:10.047554 WARNING alexa_talking_clock: ------------------------------------------------------------
2020-04-12 21:00:10.045504 WARNING alexa_talking_clock: Worker Ags: {'id': 'ab1a0d8af83b495aa32d428d8dca761b', 'name': 'alexa_talking_clock', 'objectid': '5485f12708b64a69984a88d3026f6739', 'type': 'scheduler', 'function': >, 'pin_app': True, 'pin_thread': 0, 'kwargs': {'interval': 3600, '__thread_id': 'thread-0'}}
2020-04-12 21:00:10.043761 WARNING alexa_talking_clock: Unexpected error in worker for App alexa_talking_clock:
2020-04-12 21:00:10.042038 WARNING alexa_talking_clock: ------------------------------------------------------------`

**Comment by UbhiTS** [comment]
can you please post your apps.yaml entry ?
also, if possible you appdaemon.yaml config. I've recently updated the version to 1.0.2 ... can you please update the app and try and see if this issue is still occurring ?

**Comment by stefagi** [comment]
I updated a few hours ago to version 1.0.2, but the issue still occurs.
Required files are attached below.

[atc.zip](https://github.com/UbhiTS/ad-alexatalkingclock/files/4467037/atc.zip)

**Comment by UbhiTS** [comment]
Can we please do a live debug session over chrome remote desktop, teamviewer or webex. I cant for the love of my life diagnose why it would throw a timeout error on your machine. I've asked around and no one is facing any timeout issues so it's a little difficult to say whats going on. Also, where are you located, plus what's your internet connection speed. Are you using any proxies or adblockers on your network?

**Comment by stefagi** [comment]
You have a PM .

**Comment by stefagi** [comment]
The latest version (v1.0.5) solved the issue!
No more Timeout in Log!
Great!!

**Comment by stefagi** [comment]
Oh no .. Sorry ..
Works if I set "debug: true"
When is set to false the error still appears.
Must be scheduling-related!

**Comment by UbhiTS** [comment]
I think I found the issue. Can you please update to the latest and try. Also, the latest version has some changes in the apps.yaml structure. Just a note :)

**Comment by stefagi** [comment]
Perfect! Version 2.0.2 has solved the timeout problem.
Thanks a lot!

Only a note: I was just trying the new parameters: I didn't understand if I need the new "half-hour: .." or it still works with old "announce_half_hour: ..".

**Comment by UbhiTS** [comment]
you need the new half_hour, now it's nested announce > half hour :)
